version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}miejscakultury
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5000:5000
    #  - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=meetupperdb;Username=user;Password=postgres
    #  - ASPNETCORE_HTTPS_PORTS=5001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Http:/home/app/.aspnet/https:ro
      #- ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=meetupperdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: postgres -c 'listen_addresses=*'
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data:
    external: false